// <auto-generated />
using BasicWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BasicWebAPI.Migrations
{
    [DbContext(typeof(BasicWebAPIContext))]
    [Migration("20260428182020_book_data_seeding_added")]
    partial class book_data_seeding_added
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BasicWebAPI.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearPublished")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "F. Scott Fitzgerald",
                            Title = "The Great Gatsby",
                            YearPublished = 1925
                        },
                        new
                        {
                            Id = 2,
                            Author = "Harper Lee",
                            Title = "To Kill a Mockingbird",
                            YearPublished = 1960
                        },
                        new
                        {
                            Id = 3,
                            Author = "George Orwell",
                            Title = "1984",
                            YearPublished = 1949
                        },
                        new
                        {
                            Id = 4,
                            Author = "Jane Austen",
                            Title = "Pride and Prejudice",
                            YearPublished = 1813
                        },
                        new
                        {
                            Id = 5,
                            Author = "J.D. Salinger",
                            Title = "The Catcher in the Rye",
                            YearPublished = 1951
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
